In [31]:
import pandas as pd

In [32]:
transactions = [
    100, -50, None, 200, "300", 100, -10, "invalid", 400,
    "500.5", 0, "", "700", -300, 200, "NULL"
]

In [33]:
transactions

[100,
 -50,
 None,
 200,
 '300',
 100,
 -10,
 'invalid',
 400,
 '500.5',
 0,
 '',
 '700',
 -300,
 200,
 'NULL']

In [34]:
df = pd.DataFrame(transactions, columns=["amount"])

In [35]:
df

     amount
0       100
1       -50
2      None
3       200
4       300
5       100
6       -10
7   invalid
8       400
9     500.5
10        0
11
12      700
13     -300
14      200
15     NULL

In [36]:
df = df[~df["amount"].isin(["None", "", "NULL"])]

In [37]:
#Q2. Standardize Data Types
#👉 Convert: "300" → 300 "500.5" → 500.5
#👉 Ignore: "invalid" Pattern: Transformation + validation

df["amount"] = pd.to_numeric(df["amount"], errors = "coerce")

C:\Users\trupt\AppData\Local\Temp\ipykernel_32256\1527117417.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["amount"] = pd.to_numeric(df["amount"], errors = "coerce")

In [38]:
#Q3. Keep Only Valid Numeric Records
#👉 Final list should contain only: int and float
#Pattern: Data validation

df =df.dropna()

In [39]:
df

    amount
0    100.0
1    -50.0
3    200.0
4    300.0
5    100.0
6    -10.0
8    400.0
9    500.5
10     0.0
12   700.0
13  -300.0
14   200.0

In [40]:
#Q4. Apply Business Rule Filtering
#👉 Keep only values: Greater than 0
#Pattern: Business filtering logic

df = df[df["amount"] > 0]

In [41]:
df

    amount
0    100.0
3    200.0
4    300.0
5    100.0
8    400.0
9    500.5
12   700.0
14   200.0

In [43]:
#Q5. Deduplicate Records
#👉 Remove duplicates after cleaning
#Pattern: Data deduplication

df = df.drop_duplicates()

In [44]:
df

    amount
0    100.0
3    200.0
4    300.0
8    400.0
9    500.5
12   700.0

In [50]:
#Q7. Count Records by Type
#👉 Count:how many integers
#how many floats
#attern: Basic data profiling

int_count = df["amount"].apply(lambda x: float(x).is_integer()).sum()
int_count

5

In [51]:
float_count = len(df) - int_count
float_count

1

In [53]:
#Q8. Identify Invalid Records (Important ⭐)
#👉 Create a separate list of: invalid values ("invalid", "NULL", etc.)
#Pattern: Data quality tracking

invalid_records = [
    x for x in transactions
    if pd.to_numeric(x, errors="coerce") != pd.to_numeric(x, errors="coerce")
]

In [54]:
#Q9. Sort Clean Data
#👉 Sort final cleaned data in ascending order
#Pattern: Data preparation for reporting

df = df.sort_values(by="amount")

In [55]:
def clean_transactions(data):
    import pandas as pd
    
    df = pd.DataFrame(data, columns=["amount"])
    
    # 1. Remove null-like values
    df = df[~df["amount"].isin([None, "", "NULL"])]
    
    # 2. Convert to numeric
    df["amount"] = pd.to_numeric(df["amount"], errors="coerce")
    
    # 3. Remove invalid (NaN)
    df = df.dropna()
    
    # 4. Apply business rule (>0)
    df = df[df["amount"] > 0]
    
    # 5. Remove duplicates
    df = df.drop_duplicates()
    
    # 6. Sort data
    df = df.sort_values(by="amount")
    
    return df["amount"].tolist()

In [56]:
data = [100, -50, None, 200, "300", 100, -10, "invalid", 400,
        "500.5", 0, "", "700", -300, 200, "NULL"]

print(clean_transactions(data))

[100.0, 200.0, 300.0, 400.0, 500.5, 700.0]